### PR TITLE
Controlling the time to print messages on the IOC shell with a message engine

### PR DESCRIPTION
**Pull request by marciodo**
The idea is to have a thread that controls when a message should be printed based on a configurable timeout. I tried to make the changes generic, not dependent on EPICS, but it was not fully accomplished. To activate the message engine, an IOC shell function must be used: streamMessageTimeout with the number of seconds of timeout.

The changes are fully compatible with the current version of Stream Device as, if the user doesn't call streamMessageTimeout, the behavior is still the same as before.

Instead of comparing strings, I decided to group the calls to the error macro in numeric categories. This would avoid a frenetic string comparison in the case of hundreds of messages per second being print, which could impact the performance of the message engine.

This is the data structure and the algorithm developed:

Stream Device algorithm for error messages

These are the needed changes in StreamError.h and StreamError.cc.

Original Algorithm

### CODE REVIEW

**Comment by DominicOram** [comment]
This fixes a lot of issues for us so I will pick it back up. I will do the following:
* Fix merge conflict
* Get it building in Windows - currently it won't due to the use of `pthread`, I will modify it to use `epicsThread`
* Update the documentation to include this functionality
* I'm a little worried this is being quite aggressive in how much it throws away for example if we have a number of mismatch errors in quick succession from different PVs it can sometimes be very informative to see what they were. However, I agree that checking the whole string may not be practical. I will probably at least add checking on whether errors came from the same PV.

**Comment by dirk-zimoch** [comment]
>     * I'm a little worried this is being quite aggressive in how much it throws away...
I was a little worried about the whole thing, too. :-)

**Comment by DominicOram** [comment]
Fixed merge and build issues. Was going to work on documentation and other issues with @rerpha.

@marciodo, would you be able to give myself and @rerpha permission to push to this branch?

**Comment by marciodo** [comment]
@DominicOram, I've created a collaborator invitation for both of you. Thank you a lot for working on this. I'll test the fixes later.

**Comment by DominicOram** [comment]
@dirk-zimoch and @marciodo, could we have a chat tomorrow about how to find a good balance between performance and throwing away messages?

**Comment by DominicOram** [comment]
@dirk-zimoch, @marciodo and @rerpha. Could we meet in one of the zoom breakout rooms at say 15:30 UTC?

**Comment by dirk-zimoch** [comment]
OK.

**Comment by DominicOram** [comment]
I've written up what we discussed in https://github.com/paulscherrerinstitute/StreamDevice/issues/67, I'll have a go at doing it in the next few days

**Comment by dirk-zimoch** [comment]
A different approach has been implemented.

**Pull request closed without merging**
